apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-technical-challenge.fullname" . }}
  labels:
    app: {{ include "sre-technical-challenge.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.env.PORT }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "sre-technical-challenge.name" . }}
